@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYjU2ZWU1OC1jM2M0LTQ3MDUtODMzZi1hODBiZmY1M2JkMTkiLCJhY2NvdW50SWQiOiI4NDE3NGVmYi0wNTMwLTRjNmYtOGJkZC04MDY3ZGM3NDdjNGQiLCJlbWFpbCI6InRlc3RAdGVzdC5sb2NhbCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3MTUwOTQxNCwiZXhwIjoxNjcxNTk1ODE0fQ.-GfxI8svtNh8sjrV7e-62wd6H1NBBV23gROn7mo1p8U
###
# @name Create daily entry
POST /daily-entry/create
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "sourceId": "6d182d4a-ee9c-4346-bf8c-9e9da5c6f126",
  "categoryId": 3,
  "description": "Samsung QLED 42''",
  "amount": -3144.93,
  "currency": "EUR",
  "date": "2022-12-16"
}

###
# @name List daily entries
GET /daily-entry/list/2022/12
Content-Type: application/json
Authorization: Bearer {{token}}


